In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
data=pd.read_csv('filter_data.csv')

In [3]:
data

Gender        Age    Height      Weight SMOKE           NObeyesdad
0     Female  21.000000  1.620000   64.000000    no        Normal_Weight
1     Female  21.000000  1.520000   56.000000   yes        Normal_Weight
2       Male  23.000000  1.800000   77.000000    no        Normal_Weight
3       Male  27.000000  1.800000   87.000000    no   Overweight_Level_I
4       Male  22.000000  1.780000   89.800000    no  Overweight_Level_II
...      ...        ...       ...         ...   ...                  ...
2106  Female  20.976842  1.710730  131.408528    no     Obesity_Type_III
2107  Female  21.982942  1.748584  133.742943    no     Obesity_Type_III
2108  Female  22.524036  1.752206  133.689352    no     Obesity_Type_III
2109  Female  24.361936  1.739450  133.346641    no     Obesity_Type_III
2110  Female  23.664709  1.738836  133.472641    no     Obesity_Type_III

[2111 rows x 6 columns]

In [4]:
data.SMOKE=data.SMOKE.map({'yes':1,'no':0})

In [5]:
data.Gender=data.Gender.map({'Female':1,'Male':0})

In [6]:
data

Gender        Age    Height      Weight  SMOKE           NObeyesdad
0          1  21.000000  1.620000   64.000000      0        Normal_Weight
1          1  21.000000  1.520000   56.000000      1        Normal_Weight
2          0  23.000000  1.800000   77.000000      0        Normal_Weight
3          0  27.000000  1.800000   87.000000      0   Overweight_Level_I
4          0  22.000000  1.780000   89.800000      0  Overweight_Level_II
...      ...        ...       ...         ...    ...                  ...
2106       1  20.976842  1.710730  131.408528      0     Obesity_Type_III
2107       1  21.982942  1.748584  133.742943      0     Obesity_Type_III
2108       1  22.524036  1.752206  133.689352      0     Obesity_Type_III
2109       1  24.361936  1.739450  133.346641      0     Obesity_Type_III
2110       1  23.664709  1.738836  133.472641      0     Obesity_Type_III

[2111 rows x 6 columns]

In [7]:
data.NObeyesdad.unique()

array(['Normal_Weight', 'Overweight_Level_I', 'Overweight_Level_II',
       'Obesity_Type_I', 'Insufficient_Weight', 'Obesity_Type_II',
       'Obesity_Type_III'], dtype=object)

In [8]:
data.shape

(2111, 6)

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Gender      2111 non-null   int64  
 1   Age         2111 non-null   float64
 2   Height      2111 non-null   float64
 3   Weight      2111 non-null   float64
 4   SMOKE       2111 non-null   int64  
 5   NObeyesdad  2111 non-null   object 
dtypes: float64(3), int64(2), object(1)
memory usage: 99.1+ KB


# Split independent variable and dependent variable

In [10]:
x=data.iloc[:,:-1]
y=data.iloc[:,-1:]

In [11]:
x=x.values
y=y.values

In [12]:
x

array([[  1.      ,  21.      ,   1.62    ,  64.      ,   0.      ],
       [  1.      ,  21.      ,   1.52    ,  56.      ,   1.      ],
       [  0.      ,  23.      ,   1.8     ,  77.      ,   0.      ],
       ...,
       [  1.      ,  22.524036,   1.752206, 133.689352,   0.      ],
       [  1.      ,  24.361936,   1.73945 , 133.346641,   0.      ],
       [  1.      ,  23.664709,   1.738836, 133.472641,   0.      ]])

In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y =  le.fit_transform(y)

C:\Users\HP\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [14]:
y

array([1, 1, 1, ..., 4, 4, 4])

# Split train and test dataset

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.4,random_state=10)

In [16]:
len(y_test)

845

In [17]:
count=0
for i in y_test:
    if i==0:
        count+=1
count        

103

#### Logistic Regression Model

Train Model

In [18]:
from sklearn.linear_model import LogisticRegression
log_r=LogisticRegression()
log_r.fit(x_train,y_train)

C:\Users\HP\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

Test Model

In [19]:
pre=log_r.predict(x_test)

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, pre)
print(cm)
accuracy_score(y_test, pre)

[[ 61  42   0   0   0   0   0]
 [ 41  47   0   0   0   4  21]
 [  0   0  33  42  22  16   6]
 [  0   0   0 114   0   0   0]
 [  0   0   6   0 140   0   0]
 [  4  25  23   0   8  29  45]
 [  0  10  35   0   5  18  48]]


0.5585798816568047

# K- nearest Neighbor Classification Model

Train Model

In [21]:
from sklearn.neighbors import KNeighborsClassifier
knc=KNeighborsClassifier(n_neighbors=7,metric='minkowski',p=2)
knc.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=7)

Test Model

In [22]:
pre_knc=knc.predict(x_test)

In [23]:
cm = confusion_matrix(y_test, pre_knc)
print(cm)
accuracy_score(y_test, pre_knc)

[[ 94   9   0   0   0   0   0]
 [ 24  60   1   0   0  24   4]
 [  0   0 105   6   1   2   5]
 [  0   0   3 104   7   0   0]
 [  0   0   0   4 142   0   0]
 [  1  15   3   0   0 106   9]
 [  0  11  11   4   1   9  80]]


0.8177514792899409

# Support Vector Machine Model

Train Model

In [24]:
from sklearn.svm import SVC
svm=SVC(kernel='linear',random_state=0)
svm.fit(x_train,y_train)

SVC(kernel='linear', random_state=0)

Test Model

In [25]:
pre_svm=svm.predict(x_test)

In [26]:
cm = confusion_matrix(y_test, pre_svm)
print(cm)
accuracy_score(y_test, pre_svm)

[[101   2   0   0   0   0   0]
 [ 23  79   0   0   0  11   0]
 [  0   0 107   8   0   0   4]
 [  0   0  12 102   0   0   0]
 [  0   0   0   1 145   0   0]
 [  0   9   0   0   0  81  44]
 [  0   0  20   0   0  20  76]]


0.8177514792899409

# Kernel Support Vector Machine

Train Model

In [27]:
from sklearn.svm import SVC
ksvm=SVC(kernel='rbf',random_state=0)
ksvm.fit(x_train,y_train)

SVC(random_state=0)

Test Model

In [28]:
pre_ksvm=ksvm.predict(x_test)

In [29]:
cm = confusion_matrix(y_test, pre_ksvm)
print(cm)
accuracy_score(y_test, pre_ksvm)

[[83 20  0  0  0  0  0]
 [39 43  1  0  0 26  4]
 [ 0  0 52  6 12  0 49]
 [ 0  0 16 86 12  0  0]
 [ 0  0 36 42 68  0  0]
 [ 4 30 10  0  0 51 39]
 [ 0 12 33  0  0 12 59]]


0.5230769230769231

# Naive Bayes Classifier Model

Train Model

In [30]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(x_train,y_train)

GaussianNB()

Test Model

In [31]:
pre_nb=nb.predict(x_test)

In [32]:
cm = confusion_matrix(y_test, pre_nb)
print(cm)
accuracy_score(y_test, pre_nb)

[[ 98   1   0   0   0   4   0]
 [ 53   5   0   0   7  47   1]
 [  0   1   1  30  37  50   0]
 [  0   0   1 108   0   5   0]
 [  0   1   0   1 144   0   0]
 [  6   3   0   0  31  94   0]
 [  1   0   0   8  15  91   1]]


0.5337278106508876

# Decision Tree Classifier Model

Train Model

In [33]:
from sklearn.tree import DecisionTreeClassifier
dtr=DecisionTreeClassifier(criterion='entropy',random_state=0)
dtr.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

Test Model

In [34]:
pre_dtr=dtr.predict(x_test)

In [35]:
cm = confusion_matrix(y_test, pre_dtr)
print(cm)
accuracy_score(y_test, pre_dtr)

[[ 99   4   0   0   0   0   0]
 [  6 101   0   0   0   6   0]
 [  0   0 114   1   0   0   4]
 [  0   0   5 109   0   0   0]
 [  0   0   1   0 145   0   0]
 [  0   6   0   0   0 125   3]
 [  0   0   2   0   0   8 106]]


0.9455621301775148

# Random Forest Classifier Model

Train Model

In [36]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(n_estimators=100,criterion='entropy')
rfc.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy')

Test Model

In [37]:
pre_rfc=rfc.predict(x_test)

In [38]:
cm = confusion_matrix(y_test, pre_rfc)
print(cm)
accuracy_score(y_test, pre_rfc)

[[101   2   0   0   0   0   0]
 [  6 105   0   0   0   2   0]
 [  0   0 115   1   0   0   3]
 [  0   0   0 114   0   0   0]
 [  0   0   1   0 145   0   0]
 [  0   4   0   0   0 129   1]
 [  0   0   0   0   0   7 109]]


0.9680473372781065

In [39]:
import joblib
joblib.dump(rfc,'model1.joblib')

['model1.joblib']

In [40]:
model=joblib.load('model1.joblib')

In [41]:
for i in x_test:
    print(i)
    k=model.predict([i])
    print(le.inverse_transform(k))

[  1.        21.008297   1.723587 131.929712   0.      ]
['Obesity_Type_III']
[ 0.       22.988004  1.80827  91.363293  0.      ]
['Overweight_Level_II']
[  1.        26.         1.631332 111.829957   0.      ]
['Obesity_Type_III']
[ 0.   21.    1.72 72.    0.  ]
['Normal_Weight']
[ 0.  41.   1.8 92.   0. ]
['Overweight_Level_II']
[ 1.       19.94814   1.530884 39.371523  0.      ]
['Insufficient_Weight']
[  0.        26.032416   1.824432 105.131956   0.      ]
['Obesity_Type_I']
[ 0.  19.   1.8 60.   0. ]
['Insufficient_Weight']
[ 0.   21.    1.62 70.    0.  ]
['Overweight_Level_I']
[  0.        22.580038   1.849507 121.560938   0.      ]
['Obesity_Type_II']
[ 1.       18.        1.692242 90.019501  0.      ]
['Obesity_Type_I']
[  0.    30.     1.76 112.     1.  ]
['Obesity_Type_II']
[  0.        31.36347    1.869323 127.507411   1.      ]
['Obesity_Type_II']
[ 1.       30.613586  1.645511 69.168978  0.      ]
['Overweight_Level_I']
[  1.        18.233541   1.792378 137.859737   0.   

['Normal_Weight']
[ 0.       17.908114  1.793926 59.682591  0.      ]
['Insufficient_Weight']
[ 1.       40.789529  1.549748 80.        0.      ]
['Obesity_Type_I']
[ 0.   25.    1.89 75.    0.  ]
['Normal_Weight']
[ 1.       16.270434  1.818268 47.124717  0.      ]
['Insufficient_Weight']
[  1.        21.572114   1.751067 133.845064   0.      ]
['Obesity_Type_III']
[  0.        40.501722   1.744974 111.169678   0.      ]
['Obesity_Type_II']
[  1.        21.285965   1.72692  131.335786   0.      ]
['Obesity_Type_III']
[ 1.   22.    1.56 49.    0.  ]
['Normal_Weight']
[ 0.       18.        1.738702 50.248677  0.      ]
['Insufficient_Weight']
[  0.        30.796262   1.668478 100.543983   0.      ]
['Obesity_Type_II']
[ 0.   21.    1.71 75.    0.  ]
['Overweight_Level_I']
[  0.        29.633715   1.834842 105.19936    0.      ]
['Obesity_Type_I']
[ 1.   18.    1.63 63.    0.  ]
['Normal_Weight']
[  1.        22.846357   1.757442 133.365094   0.      ]
['Obesity_Type_III']
[ 1.       18.

['Obesity_Type_III']
[ 1.       16.240576  1.616533 65.062945  0.      ]
['Overweight_Level_I']
[  0.        22.832105   1.86714  121.835883   0.      ]
['Obesity_Type_II']
[  0.        28.255199   1.816547 120.699119   0.      ]
['Obesity_Type_II']
[ 1.       38.692265  1.548178 62.341438  0.      ]
['Overweight_Level_I']
[ 0.       18.        1.739344 50.951444  0.      ]
['Insufficient_Weight']
[ 1.       19.483036  1.53777  42.        0.      ]
['Insufficient_Weight']
[  1.        20.394082   1.747714 128.148108   0.      ]
['Obesity_Type_III']
[ 1.       18.        1.692913 89.93889   0.      ]
['Obesity_Type_I']
[ 0.       28.39124   1.81006  87.286783  0.      ]
['Overweight_Level_I']
[  0.        24.63474    1.829757 120.980508   0.      ]
['Obesity_Type_II']
[ 0.       24.108711  1.7      80.761409  0.      ]
['Overweight_Level_II']
[  1.        21.330178   1.747987 147.296186   0.      ]
['Obesity_Type_III']
[ 0.       20.738469  1.759933 55.003417  0.      ]
['Insufficient_W

['Overweight_Level_I']
[ 0.  23.   1.7 69.   0. ]
['Normal_Weight']
[ 0.   24.    1.66 67.    0.  ]
['Normal_Weight']
[ 1.   19.    1.69 70.    0.  ]
['Normal_Weight']
[ 1.   21.    1.66 57.    0.  ]
['Normal_Weight']
[  1.        20.520992   1.668642 124.704781   0.      ]
['Obesity_Type_III']
[ 1.       22.422674  1.70011  50.173425  0.      ]
['Insufficient_Weight']
[  1.        18.976968   1.759091 133.903612   0.      ]
['Obesity_Type_III']
[ 0.       19.179932  1.637537 70.        0.      ]
['Overweight_Level_I']
[ 0.   22.    1.78 89.8   0.  ]
['Overweight_Level_II']
[ 0.       21.18354   1.72     80.555875  0.      ]
['Overweight_Level_II']
[ 0.      20.       1.81748 85.       0.     ]
['Overweight_Level_I']
[  1.        25.493586   1.673665 104.704707   0.      ]
['Obesity_Type_III']
[  1.        26.         1.633887 111.878132   0.      ]
['Obesity_Type_III']
[ 0.       21.086512  1.863685 89.558854  0.      ]
['Overweight_Level_I']
[  0.        24.408805   1.779547 118.7400

['Obesity_Type_II']
[  0.        26.844812   1.69151  102.59518    0.      ]
['Obesity_Type_II']
[ 1.   32.    1.57 57.    0.  ]
['Normal_Weight']
[ 1.       18.236087  1.62     69.3899    0.      ]
['Overweight_Level_I']
[ 0.   23.    1.62 58.    0.  ]
['Normal_Weight']
[ 1.       16.941489  1.551288 54.93242   0.      ]
['Normal_Weight']
[  0.    33.     1.83 113.     0.  ]
['Obesity_Type_II']
[  0.        18.         1.787733 108.019211   0.      ]
['Obesity_Type_I']
[ 1.  23.   1.5 55.   0. ]
['Normal_Weight']
[ 1.       32.501143  1.675979 74.959747  0.      ]
['Overweight_Level_I']
[ 0.       21.        1.712061 75.        0.      ]
['Overweight_Level_I']
[ 1.       17.823438  1.708406 50.        0.      ]
['Insufficient_Weight']
[ 0.       18.        1.70165  50.157707  0.      ]
['Insufficient_Weight']
[ 0.       25.45763   1.837399 95.952027  0.      ]
['Overweight_Level_II']
[ 0.       22.052152  1.792527 89.994415  0.      ]
['Overweight_Level_II']
[  1.        19.137495   1

['Overweight_Level_II']
[ 0.       19.329542  1.767335 55.700497  0.      ]
['Insufficient_Weight']
[  1.        22.77789    1.661415 120.748213   0.      ]
['Obesity_Type_III']
[  0.    21.     1.85 125.     0.  ]
['Obesity_Type_II']
[ 1.   61.    1.65 66.    0.  ]
['Overweight_Level_I']
[  0.        29.687488   1.909198 129.679131   0.      ]
['Obesity_Type_II']
[  0.        27.474245   1.84342  120.420406   0.      ]
['Obesity_Type_II']
[ 0.       20.406066  1.868931 63.199726  0.      ]
['Normal_Weight']
[ 1.  18.   1.6 55.   0. ]
['Normal_Weight']
[  1.        19.885655   1.763343 133.952675   0.      ]
['Obesity_Type_III']
[  1.        24.449655   1.635062 113.277388   0.      ]
['Obesity_Type_III']
[ 1.       39.135634  1.507867 79.58958   0.      ]
['Obesity_Type_I']
[  0.        21.721507   1.849998 122.119682   0.      ]
['Obesity_Type_II']
[  1.        23.76197    1.69135  114.480696   0.      ]
['Obesity_Type_III']
[  0.        20.9859     1.780503 103.189532   0.      ]
['

['Overweight_Level_I']
[  1.        26.         1.60937  105.407313   0.      ]
['Obesity_Type_III']
[ 1.       19.054008  1.556611 39.695295  0.      ]
['Insufficient_Weight']
[  1.        20.700876   1.68838  121.889803   0.      ]
['Obesity_Type_III']
[  1.        26.         1.627567 107.482662   0.      ]
['Obesity_Type_III']
[ 1.   16.    1.57 49.    0.  ]
['Normal_Weight']
[ 1.   38.    1.64 59.8   0.  ]
['Normal_Weight']
[ 1.       17.065445  1.647811 49.603807  0.      ]
['Insufficient_Weight']
[  1.        26.         1.643421 111.939983   0.      ]
['Obesity_Type_III']
[ 0.  18.   1.8 72.   0. ]
['Normal_Weight']
[  1.        21.772251   1.732951 132.904884   0.      ]
['Obesity_Type_III']
[ 0.   21.    1.62 70.    0.  ]
['Overweight_Level_I']
[ 1.  17.   1.6 59.   0. ]
['Normal_Weight']
[  0.        31.190219   1.842812 125.973927   1.      ]
['Obesity_Type_II']
[  1.        25.540865   1.678201 109.900472   0.      ]
['Obesity_Type_III']
[ 0.       27.349745  1.835271 97.5